### ISSUE TITLE
Using MetricAffectSpans to get different typeface leads to wrong padding

### ISSUE THREAD

**Issue by Zordid** [JohnPersano/SuperToasts#23]
Because of the missing Typeface-setting option, I tried a real clue:
Setting texts using SpannableStrings that include a different `MetricAffectingSpan` (see http://stackoverflow.com/a/15181195/273456)

But when doing that, the padding around the text gets really small, the toasts become extremely thin...
Could you help?

**Comment by JohnPersano** [comment]
@Zordid I'm not sure if this is still an issue so I am closing this. 

P.S.I have consolidated the managers into a single class called the Toaster in honor of your [comment](https://github.com/JohnPersano/SuperToasts/issues/23#issuecomment-33876350)
