### ISSUE TITLE
Static creator for reference holder

### ISSUE THREAD

**Issue by aran-arunakiri** [JohnPersano/SuperToasts#33]
The creator method in parcelable referenceholder should be static. Now it crashes when you those need need to be restored with the following exception "expected receiver of type com.github.johnpersano.supertoasts.SuperCardToast$ReferenceHolder, but got null"

**Comment by IlyaEremin** [comment]
I get `expected receiver of type com.github.johnpersano.supertoasts.SuperCardToast$ReferenceHolder, but got null` error, but I can't understand why. I use last 1.3.4aar. Is it have 4c8d4ac changes?
