### ISSUE TITLE
Floating SuperCardToast?

### ISSUE THREAD

**Issue by lgvalle** [JohnPersano/SuperToasts#37]
Have you thought in adding a 'floating' style to SuperCardToasts? Something like what Crouton does. 
I really like SuperCardToast and the customization possibilities, but two things made me finally discard it:

- The need to add a new layout in my root view
- Because SuperCardToast moves everything down, if working with lists this forces the adapter to repaint (and remeasure) everything over and over.

It would be nice to have the possibility to display the card over the current layout

**Comment by JohnPersano** [comment]
Igvalle,

Thanks for your continuing support as always. I have added this feature in version 2.0. SuperCardToasts have had all functionality absorbed into SuperActivityToasts which can now be shown within a ViewGroup (like SuperCardToasts) or placed on top of an Activity's content.

Thanks,
John

**Comment by lgvalle** [comment]
@JohnPersano no problem! thanks to you for keep helping the community with great opensource stuff
