### ISSUE TITLE
API inconsistent

### ISSUE THREAD

**Issue by alexeyvasilyev** [JohnPersano/SuperToasts#38]
Change from setTextSize(int) to setTextSize(float).

mMessageTextView.setTextSize expects float, not int.

// SuperToast
    public void setTextSize(int textSize) {

        mMessageTextView.setTextSize(textSize);

    }

**Comment by JohnPersano** [comment]
alexeyvasilyev,

Thank you for the report. The API is being rewritten from the ground up. This will be addressed in version 2.0 of the library.

Thanks,

John
