### ISSUE TITLE
SuperCardToast with ViewPager

### ISSUE THREAD

**Issue by dazito** [JohnPersano/SuperToasts#43]
I've a Fragment that holds a ViewPager. This ViewPager has 2 fragments (let's call them, "FragmentA" and "FragmentB" as tabbed views.

Both FragmentA and FragmentB have:

<LinearLayout  
    android:id="@+id/card_container"  
    android:layout_width="match_parent"  
    android:layout_height="wrap_content"  
    android:background="#15000000"  
    android:orientation="vertical" />

As root on their XML layout.
When FragmentB is on the screen and the user presses something in there to fire a Toast the Toast is displayed, always, on FragmentA (which is not visible to the user) and not in the FragmentB (where the user is).

It should fire the Toasts in the "on screen" fragment.

Is this a bug? I can't find out a solution for this and I can't find anything on google regarding this issue.

**Comment by JohnPersano** [comment]
dazito,

I'm making this easier in version 2.0 of the library. Thank you very much for the report and code!

John
