### ISSUE TITLE
SuperActivityToast now showing (and not clickable) occasionally ?

### ISSUE THREAD

**Issue by skadavan** [JohnPersano/SuperToasts#45]
I am using SuperActivityToast to show a confirmation with an optional info button (which launches another activity).

Occasionally the toast doesn't come up. Occasionally it comes up but the button is not clickable. Noticed this happens when we try using it frequently. I am using it from a fragment. Any clues ?

Code below:

		subscribeConfirmationToast = new SuperActivityToast(getActivity(), SuperToast.Type.BUTTON);
		subscribeConfirmationToast.setTouchToDismiss(true);
		subscribeConfirmationToast.setText(getResources().getString(R.string.button_subscribe_confirmation));
		subscribeConfirmationToast.setButtonIcon(R.drawable.ic_action_database, 
				getResources().getString(R.string.page_title_subscribed));
		subscribeConfirmationToast.setDuration(SuperToast.Duration.SHORT);
		subscribeConfirmationToast.setOnClickWrapper(new OnClickWrapper(this.getClass().getName(), new OnClickListener() {
			@Override
			public void onClick(View view, Parcelable token) {
				SuperActivityToast.cancelAllSuperActivityToasts();
				EventBus.getDefault().post(new Event.ShowMyShowsClicked(getActivity()));	// This will launch another activity.			
			}
		}));

	public void onEventMainThread(Event.ShowSubscribed event) {
		// some other UI updations
		if(subscribeConfirmationToast != null) {
			subscribeConfirmationToast.show();
		}
       }

**Comment by JohnPersano** [comment]
tbruyelle,

You are correct. While the SuperActivityToasts were not specifically designed as a one shot, it is best practice to reuse the same one. I will make this more clear in the documentation.

Thanks,

John
