### ISSUE TITLE
Request: Please remove unused resources from the library project

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [JohnPersano/SuperToasts#49]
For example "dummy_layout.xml" . 
If you just need its id to be declared, just declare an id in a "ids.xml" file.

In order to find all of the unused resources, I suggest to run Lint (and on the way to also check other warnings of it).

**Comment by JohnPersano** [comment]
AndroidDeveloperLB,
All unused resources have been removed in version 2.0.
Thanks,
- John

**Comment by AndroidDeveloperLB** [comment]
Thank you
