### ISSUE TITLE
The gradle error

### ISSUE THREAD

**Issue by 38017032** [JohnPersano/SuperToasts#63]

**Comment by JohnPersano** [comment]
38017032,

I'm getting a similar error. I'm reworking the Gradle file to fix this issue and update everything to the most recent versions. 

Thanks,

John

**Comment by genaks** [comment]
No solution for this yet?

**Comment by DarkComet007** [comment]
1.Delete these lines:

```java
artifactId = "supertoasts"
```

```java
  repository(url: sonatypeRepo) {
            authentication(userName: sonatypeUsername,
                    password: sonatypePassword)
        }
```

2. Change Gradle build version in classpath to the your apps version:

     ```java
  dependencies{
        classpath 'com.android.tools.build:gradle:0.9.+'
	}
```
 I changed it to: 
```java
dependencies{
        classpath 'com.android.tools.build:gradle:1.3.+'
	}
```

3. Update compileSdkVersion and buildToolsVersion in supertoast build.gradle to your apps build.gradle. This worked for me:
```java
    compileSdkVersion 23
    buildToolsVersion "23.0.0"
```
