### ISSUE TITLE
duration infinite?

### ISSUE THREAD

**Issue by DavidMont** [JohnPersano/SuperToasts#66]
duration infinite?

**Comment by JohnPersano** [comment]
DavidMont,

Thanks for the input. I am not entirely sure what you are asking. SuperActivityToasts can be made indeterminate through the use of:

`superActivityToast.setIndeterminate(true);`

While SuperToasts can technically be made indeterminate, I will not add that functionality to the library as it will allow for lingering messages across all applications until the calling application's process ends.

Thanks,
John

**Comment by AndroidDeveloperLB** [comment]
If you want infinite duration, consider something that's attached to the activity, like Snakbar. Example:

       Snackbar.make(v, "Loading...", Snackbar.LENGTH_INDEFINITE).show();
