### ISSUE TITLE
help

### ISSUE THREAD

**Issue by klob** [JohnPersano/SuperToasts#67]
+--+
could u give your Gmail
I have some problem when using SuperToast
I want to ask u some questions
thx

**Comment by klob** [comment]
mine is kloblic@gmail.com

**Comment by JohnPersano** [comment]
klob,
Thanks for the input. Unfortunately, I cannot offer one-to-one support through email. Version 2.0 was released which fixed many issues. If you have the same issue with the new version, please open an issue stating specifically what you are experiencing or post a question on StackOverflow.
Thanks,
- John
