### ISSUE TITLE
Center text in SuperCardToast

### ISSUE THREAD

**Issue by andytriboletti** [JohnPersano/SuperToasts#70]
I'd like my text to be centered instead of left-aligned when using SuperCardToast.  Is this possible?

**Comment by JohnPersano** [comment]
andytriboletti,
Thanks for the input. Version 2.0 absorbed all SuperCardToast functionality into the SuperActivityToast class, however it is still not possible to center align the text. I will open a feature request and reference it here.
Thanks,
- John

**Comment by JohnPersano** [comment]
Referenced in issue #85

**Comment by hangryfabian** [comment]
There should be a method called SetAlignment; but here's what I did to center it is as a temporary fix.
Great library btw, keep it up!  

View mainView = superToast.getView();
        TextView msgTextView = (TextView) mainView.findViewById(com.github.johnpersano.supertoasts.library.R.id.message);
        TableRow.LayoutParams params = new TableRow.LayoutParams(TableRow.LayoutParams.MATCH_PARENT, TableRow.LayoutParams.WRAP_CONTENT, 1f);
        msgTextView.setLayoutParams(params);
        msgTextView.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);
