### ISSUE TITLE
Change circle progress icon and background of the internal bar

### ISSUE THREAD

**Issue by abanjo** [JohnPersano/SuperToasts#73]
Hi,
your library works great! Great job!
But, i have some problems.
1) As i see, the background of the bar can be only one of the 8 custom color ( es : SuperToast.Background.WHITE ).
This is a limitation. Do you plan in the future to let developer to choose it?
2) In your demo application the circle icon animation is white ... but when i put the code in my application it is cyan ... i don't know how to change it!. Actually it works, but the color combination are awfull.

Thanks!
Davide

**Comment by JohnPersano** [comment]
Davide,
Thanks for the input. SuperToasts version 2.0 adds the ability to use any RGB value in addition to its presets. In devices using API 21, SuperToasts version 2.0 adds the ability to change the ProgressBar color using:

`superActivityToast.setProgressBarColor(Color.BLUE);`

Thanks,
- John
