### ISSUE TITLE
setBackgroundColor

### ISSUE THREAD

**Issue by thomasMary** [JohnPersano/SuperToasts#74]
Is there any reason for restricting us to your SuperToast.Background enum? It would be good to be able set my own color.
So having a new method that simply set the backgroundColor like that:
mRootLayout.setBackgroundColor(Color.parseColor("#F4F4F4"))

PS: great job

**Comment by JohnPersano** [comment]
thomasMary,
Thanks for the input. I can't honestly remember my logic behind it so I'll assume it was made in error. Version 2.0 allows background to be any RGB value in addition to its presets.
Thanks,
- John
