### ISSUE TITLE
setAnimation

### ISSUE THREAD

**Issue by sindri55** [JohnPersano/SuperToasts#76]
Please put "setAnimations" as public. 

                                    SuperToast s = new SuperToast(getActivity());
                                    s.setGravity(Gravity.CENTER, 0, 0);
                                    s.setText("lgfda");
                                    s.setDuration(2);
      Not found ->                  s.setStyle(......);
                                    s.setAnimations(SuperToast.Animations.FLYIN);
                                    s.setBackground(getResources().getColor(R.color.wise_dark_orange));
                                    s.show();

**Comment by JohnPersano** [comment]
sindro55,
Thanks for the input. The `setAnimations()` method should have been public, I'm not sure why it wouldn't be. In version 2.0, the method is certainly made public.
Thanks,
- John
