### ISSUE TITLE
Toasts don't display above the lock screen on Lollipop devices

### ISSUE THREAD

**Issue by NipponMonkey** [JohnPersano/SuperToasts#77]
For some reason Android toasts and your super toasts do not appear above the lockscreen anymore - only behind it (on Lollipop). It would be great if you can find a fix for this as my app currently uses this feature for feed back to the user.

**Comment by JohnPersano** [comment]
NipponMonkey,
Thanks for the input. SuperToasts share some commonalities with the stock Android Toasts, therefore I would expect this behavior. Unfortunately, I do not think it is possible to show a message on top of the lock screen without requiring a specific permission which I would like to avoid. I will look into it and see if there is a workaround.
Thanks,
- John

**Comment by JohnPersano** [comment]
After looking into this, I believe it is related to issue #58. I will close this unless it is proven that it is not related.

John
