### ISSUE TITLE
Dismiss toast if shown

### ISSUE THREAD

**Issue by darkovski88** [JohnPersano/SuperToasts#79]
Hello,
I need to dismiss a SuperToast if shown when app is being closed, so if a supertoast is shown i dismiss it. I try to do a dismiss on the object shown but it still not removed.
Can anoyone help me?

Here is my code:

` static SuperToast superToast;
    public static void showErrorMsg(Context context, String errorName) {
        try {
            superToast = new SuperToast(context);
            superToast.setAnimations(SuperToast.Animations.FLYIN);
            superToast.setDuration(SuperToast.Duration.VERY_SHORT);
            superToast.setBackground(R.color.error_color);
            superToast.setTextSize(SuperToast.TextSize.MEDIUM);
            superToast.setTextColor(ContextCompat.getColor(context, R.color.white));
            superToast.setText(errorName);
            superToast.show();
        } catch (IllegalArgumentException ex) {
            ex.printStackTrace();
        }
    }

    public static void clearSuperToast() {
        if (superToast != null)
            if (superToast.isShowing())
                superToast.dismiss();
    }`

I call  `clearSuperToast()` on back pressed and its not working

**Comment by JohnPersano** [comment]
darkovski88,
Thanks for reporting this. I do not recommend making a SuperToast static. I have not tested this and cannot guarantee correct behavior when doing so. In your onDestroy() method, call 

 `SuperActivityToast.cancelAllSuperToasts();`

This will ensure all SuperToasts and SuperActivityToasts are canceled and dismissed properly.
Thanks,
- John
